# Generated by Django 4.1 on 2023-02-19 17:24

from django.db import migrations, models
import grace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("phone", models.CharField(max_length=200, unique=True)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("amount", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("message", models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("message", models.TextField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("link", models.URLField()),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image2", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image3", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image4", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image5", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image6", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Gallery2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("title2", models.CharField(max_length=200, unique=True)),
                ("title3", models.CharField(max_length=200, unique=True)),
                ("title4", models.CharField(max_length=200, unique=True)),
                ("title5", models.CharField(max_length=200, unique=True)),
                ("title6", models.CharField(max_length=200, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image2", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image3", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image4", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image5", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image6", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Pastors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("position", models.CharField(max_length=200, unique=True)),
                ("fb_account", models.CharField(max_length=200, unique=True)),
                ("twitter_account", models.CharField(max_length=200, unique=True)),
                ("ig_account", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to=grace.models.content_file_name
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("title", models.CharField(max_length=200, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Podcasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="audio/%Y/%m/%d/"
                    ),
                ),
                (
                    "audio_image",
                    models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now=True)),
                ("video_link", models.URLField(max_length=500)),
                ("image", models.ImageField(upload_to="users/%Y/%m/%d/")),
            ],
        ),
    ]
